
################### English Navigation ########################
[[main]]
name = "About"
url = "#about"
weight = 1

[[main]]
name = "Technology"
url = "#services"
weight = 2

[[main]]
name = "Market"
url = "#portfolio"
weight = 3

[[main]]
name = "Team"
url = "#team"
weight = 4

[[main]]
name = "News"
url = "#blog"
weight = 5

[[main]]
name = "Contact"
url = "#contact"
weight = 6


[[main]]
name = "Dropdown"
weight = 6
hasChildren = true

[[main]]
parent = "Dropdown"
name = "Dropdown 1"
url = "#"
weight = 1

[[main]]
parent = "Dropdown"
name = "Dropdown 2"
url = "#"
weight = 2

[[main]]
name = "themefisher"
url = "https://themefisher.com/"
weight = 8

