[hugoVersion]
extended = true
min = "0.147.2"


[[imports]]
  # This is the main Meghna theme module
  path = "github.com/themefisher/meghna-hugo"

[[imports]]
  # This is the theme's required dependency for image handling
  path = "github.com/gethugothemes/hugo-modules/images"
