baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Nimverta"
theme = "meghna-hugo"

[module]
  [[module.imports]]
    path = "github.com/themefisher/meghna-hugo"

[params]
  author = "Nimverta"
  description = "Developing safe and effective long-term therapies for bone disease."
  logo = "images/logo.png" # We will add this image later
  
  # Main Navigation
  [menu]
    [[menu.main]]
      name = "About"
      URL = "#about"
      weight = 1
    [[menu.main]]
      name = "Technology"
      URL = "#service"
      weight = 2
    [[menu.main]]
      name = "Market"
      URL = "#portfolio"
      weight = 3
    [[menu.main]]
      name = "Team"
      URL = "#team"
      weight = 4
    [[menu.main]]
      name = "News"
      URL = "#blog"
      weight = 5
    [[menu.main]]
      name = "Contact"
      URL = "#contact"
      weight = 6

